CONVERSION_VAR = {"__ac_b_name__": "ac_b_name",
                  "__ac_e_name__": "ac_e_name",
                  "__b_name__": "b_name",
                  "__e_name__": "e_name",
                  "__dob__": "dob",
                  " __f_name__": "f_name",
                  "__m_name__": "m_name",
                  " __s_name__": "s_name",
                  "__nationality__": "nationality",
                  "__post__": "pre_post_office",
                  "__thana__": "pre_upozila",
                  "__dist__": "pre_district",
                  "__ppost__": "per_post_office",
                  "__pthana__": "per_upozila",
                  "__pdist__": "per_district",
                  "__n_name__": "n_b_name",
                  "__n_dob__": "n_dob",
                  "__n_f_name__": "n_f_name",
                  "__n_m_name__": "n_m_,name",
                  "__n_post__": "n_pre_post_office",
                  "__n_thana__": "n_pre_upozila",
                  "__n_dist__": "n_pre_district",
                  "__n_national_id__": "n_national_id",
                  "__occupation__": "occupation",
                  "__income__": "income",
                  "__source__": "source",
                  "__national_id__": "national_id",
                  "__dccnt__": "depo_cash_txn",
                  "__dtcnt__": "depo_trans_txn",
                  "__dcamt__": "depo_cash_txn_amt",
                  "__dtamt__": "depo_trans_txn_amt",
                  "__wdccnt__": "wd_cash_txn",
                  "__wdtcnt__": "wd_trans_txn",
                  "__wdcamt__": "wd_cash_txn_amt",
                  "__wdtamt__": "wd_trans_txn_amt"}

