# Generated by Django 4.1.2 on 2023-06-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100)),
                ('dob', models.TextField(blank=True, max_length=100)),
                ('f_name', models.TextField(blank=True, max_length=100)),
                ('m_name', models.TextField(blank=True, max_length=100)),
                ('s_name', models.TextField(blank=True, max_length=100)),
                ('occupation', models.TextField(blank=True, max_length=100)),
                ('village', models.TextField(blank=True, max_length=100)),
                ('post_office', models.TextField(blank=True, max_length=100)),
                ('thana', models.TextField(blank=True, max_length=100)),
                ('district', models.TextField(blank=True, max_length=100)),
                ('division', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
