# Generated by Django 4.1.2 on 2023-06-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remit', '0002_alter_customcustomer_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcustomer',
            name='district',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customcustomer',
            name='division',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customcustomer',
            name='f_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customcustomer',
            name='m_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customcustomer',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customcustomer',
            name='post_office',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customcustomer',
            name='s_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customcustomer',
            name='thana',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customcustomer',
            name='village',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
