# Generated by Django 4.1.2 on 2023-06-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remit', '0003_alter_customcustomer_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customcustomer',
            old_name='f_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='customcustomer',
            old_name='m_name',
            new_name='mother_name',
        ),
        migrations.RenameField(
            model_name='customcustomer',
            old_name='s_name',
            new_name='spouse_name',
        ),
    ]
