# Generated by Django 3.1.7 on 2023-04-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.TextField(blank=True, max_length=100)),
                ('e_name', models.TextField(blank=True, max_length=100)),
                ('dob', models.TextField(blank=True, max_length=100)),
                ('f_name', models.TextField(blank=True, max_length=100)),
                ('m_name', models.TextField(blank=True, max_length=100)),
                ('s_name', models.TextField(blank=True, max_length=100)),
                ('occupation', models.TextField(blank=True, max_length=100)),
                ('pre_division', models.TextField(blank=True, max_length=100)),
                ('pre_district', models.TextField(blank=True, max_length=100)),
                ('pre_rmo', models.TextField(blank=True, max_length=100)),
                ('pre_citycorp', models.TextField(blank=True, max_length=100)),
                ('pre_upozila', models.TextField(blank=True, max_length=100)),
                ('pre_union_ward', models.TextField(blank=True, max_length=100)),
                ('pre_mouza_moholla', models.TextField(blank=True, max_length=100)),
                ('pre_additional_mouza_moholla', models.TextField(blank=True, max_length=100)),
                ('pre_ward_for_union_porishod', models.TextField(blank=True, max_length=100)),
                ('pre_village_road', models.TextField(blank=True, max_length=100)),
                ('pre_additional_village_road', models.TextField(blank=True, max_length=100)),
                ('pre_home_holding_no', models.TextField(blank=True, max_length=100)),
                ('pre_post_office', models.TextField(blank=True, max_length=100)),
                ('pre_postal_code', models.TextField(blank=True, max_length=100)),
                ('pre_region', models.TextField(blank=True, max_length=100)),
                ('per_division', models.TextField(blank=True, max_length=100)),
                ('per_district', models.TextField(blank=True, max_length=100)),
                ('per_rmo', models.TextField(blank=True, max_length=100)),
                ('per_city_corporation_or_municipality', models.TextField(blank=True, max_length=100)),
                ('per_upozila', models.TextField(blank=True, max_length=100)),
                ('per_union_ward', models.TextField(blank=True, max_length=100)),
                ('per_mouza_moholla', models.TextField(blank=True, max_length=100)),
                ('per_additional_mouza_moholla', models.TextField(blank=True, max_length=100)),
                ('per_ward_for_union_porishod', models.TextField(blank=True, max_length=100)),
                ('per_village_road', models.TextField(blank=True, max_length=100)),
                ('per_additional_village_road', models.TextField(blank=True, max_length=100)),
                ('per_home_holding_no', models.TextField(blank=True, max_length=100)),
                ('per_post_office', models.TextField(blank=True, max_length=100)),
                ('per_postal_code', models.TextField(blank=True, max_length=100)),
                ('per_region', models.TextField(blank=True, max_length=100)),
                ('blood_group', models.TextField(blank=True, max_length=100)),
                ('national_id', models.TextField(blank=True, max_length=100)),
                ('pin', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
