# Generated by Django 3.1.7 on 2023-05-07 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_openning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SporceOfIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='income',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation_nid',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='tp_depo_cash_txn',
            field=models.TextField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='tp_depo_cash_txn_amt',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='tp_depo_trans_txn',
            field=models.TextField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='tp_depo_trans_txn_amt',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='tp_wd_cash_txn',
            field=models.TextField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='tp_wd_cash_txn_amt',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='tp_wd_trans_txn',
            field=models.TextField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='tp_wd_trans_txn_amt',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(choices=[('FAR', 'কৃষক')], default='', max_length=6),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.TextField(blank=True, max_length=100)),
                ('b_name', models.TextField(blank=True, max_length=100)),
                ('ac_number', models.TextField(blank=True, max_length=100)),
                ('nominee', models.TextField(blank=True, max_length=100)),
                ('init_depo', models.TextField(blank=True, max_length=100)),
                ('init_depo_word', models.TextField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_openning.customer')),
            ],
        ),
    ]
