# Generated by Django 3.1.7 on 2023-05-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_openning', '0002_auto_20230507_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tp_depo_cash_txn',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tp_depo_cash_txn_amt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tp_depo_trans_txn',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tp_depo_trans_txn_amt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tp_wd_cash_txn',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tp_wd_cash_txn_amt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tp_wd_trans_txn',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tp_wd_trans_txn_amt',
        ),
        migrations.AddField(
            model_name='account',
            name='tp_depo_cash_txn',
            field=models.TextField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='tp_depo_cash_txn_amt',
            field=models.TextField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='account',
            name='tp_depo_trans_txn',
            field=models.TextField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='tp_depo_trans_txn_amt',
            field=models.TextField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='account',
            name='tp_wd_cash_txn',
            field=models.TextField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='tp_wd_cash_txn_amt',
            field=models.TextField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='account',
            name='tp_wd_trans_txn',
            field=models.TextField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='tp_wd_trans_txn_amt',
            field=models.TextField(blank=True, max_length=9),
        ),
    ]
