# Generated by Django 3.1.7 on 2023-05-08 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_openning', '0003_auto_20230507_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='tp_depo_cash_txn',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tp_depo_cash_txn_amt',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tp_depo_trans_txn',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tp_depo_trans_txn_amt',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tp_wd_cash_txn',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tp_wd_cash_txn_amt',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tp_wd_trans_txn',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tp_wd_trans_txn_amt',
        ),
        migrations.CreateModel(
            name='TxnProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_depo_cash_txn', models.TextField(blank=True, max_length=3)),
                ('tp_depo_cash_txn_amt', models.TextField(blank=True, max_length=9)),
                ('tp_depo_trans_txn', models.TextField(blank=True, max_length=3)),
                ('tp_depo_trans_txn_amt', models.TextField(blank=True, max_length=9)),
                ('tp_wd_cash_txn', models.TextField(blank=True, max_length=3)),
                ('tp_wd_cash_txn_amt', models.TextField(blank=True, max_length=9)),
                ('tp_wd_trans_txn', models.TextField(blank=True, max_length=3)),
                ('tp_wd_trans_txn_amt', models.TextField(blank=True, max_length=9)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_openning.account')),
            ],
        ),
    ]
