# Generated by Django 3.1.7 on 2023-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_openning', '0004_auto_20230508_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='income',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='source',
        ),
        migrations.AddField(
            model_name='account',
            name='income',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='nationality',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='source',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
