# Generated by Django 3.1.7 on 2023-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_openning', '0006_auto_20230508_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
