# Generated by Django 3.1.7 on 2023-05-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_openning', '0007_auto_20230508_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SporceOfIncome',
            new_name='SourceOfIncome',
        ),
    ]
