# Generated by Django 3.1.7 on 2023-05-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_openning', '0008_auto_20230508_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='occupation',
        ),
        migrations.AddField(
            model_name='account',
            name='occupation',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
