# Generated by Django 3.1.7 on 2023-05-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_openning', '0009_auto_20230508_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txnprofile',
            old_name='tp_depo_cash_txn',
            new_name='depo_cash_txn',
        ),
        migrations.RenameField(
            model_name='txnprofile',
            old_name='tp_depo_cash_txn_amt',
            new_name='depo_cash_txn_amt',
        ),
        migrations.RenameField(
            model_name='txnprofile',
            old_name='tp_depo_trans_txn',
            new_name='depo_trans_txn',
        ),
        migrations.RenameField(
            model_name='txnprofile',
            old_name='tp_depo_trans_txn_amt',
            new_name='depo_trans_txn_amt',
        ),
        migrations.RenameField(
            model_name='txnprofile',
            old_name='tp_wd_cash_txn',
            new_name='wd_cash_txn',
        ),
        migrations.RenameField(
            model_name='txnprofile',
            old_name='tp_wd_cash_txn_amt',
            new_name='wd_cash_txn_amt',
        ),
        migrations.RenameField(
            model_name='txnprofile',
            old_name='tp_wd_trans_txn',
            new_name='wd_trans_txn',
        ),
        migrations.RenameField(
            model_name='txnprofile',
            old_name='tp_wd_trans_txn_amt',
            new_name='wd_trans_txn_amt',
        ),
    ]
