# Generated by Django 3.1.7 on 2023-05-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_openning', '0010_auto_20230508_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AccType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='goal',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
